blog2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls', namespace='blog')),
    path('clicks/', include('clicks.urls', namespace='clicks')),
]

clicks/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import *

app_name = 'clicks'

urlpatterns = [
    path('', clicks_view, name='clicks')    
]

posts/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import *


app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='posts'),
]

clicks/models.py
from django.db import models

# Create your models here.
class Click(models.Model):
    clicks = models.PositiveIntegerField()

posts/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=128, verbose_name="Заголовок")
    text=models.TextField(blank=False, verbose_name="Текст")
    published=models.BooleanField(default=False, verbose_name="Опубликовано")
    publish_date=models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")
    change_date=models.DateTimeField(auto_now=True, verbose_name="Дата изменения")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор")
    likes = models.ManyToManyField(User, related_name="liked_posts", verbose_name="Лайки")

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["-publish_date", "-change_date"]

clicks/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Click

class ClickForm(forms.ModelForm):
    class Meta:
        model = Click
        fields = ('clicks',)

clicks/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .forms import ClickForm
from .models import Click

def clicks_view(request):
    click = Click.objects.all()
    form = None
    
    if request.is_ajax():
        clicks = 0
        if len(click) == 0:
            click = Click()
            click.clicks = request.GET['clicks']
            clicks = request.GET['clicks']
            clisk.save()
        else:
            click_old = Click.objects.get(pk=1)
            click_old.clicks += request.GET['clicks']
            clicks = click_old.clicks
            click_old.save()
        return JsonResponse({'clicks': clicks})
    else:
        form = ClickForm(request.GET)
        if form.is_valid():
            
            print(f'length of clicks is {len(click)}')
            if len(click) == 0:
                form.save()
            else:
                click_new = form.save(commit=False)
                click_old = Click.objects.get(pk=1)
                click_old.clicks += click_new.clicks
                click_old.save()
                
        form = ClickForm()
        
        click = Click.objects.get(pk=1)
        
    context = {'form': form, 'clicks': click.clicks}
    return render(request, 'clicks/index.html', context)

posts/views.py
from django.shortcuts import render

# Create your views here.
from posts.models import Post
from django.core.paginator import Paginator


def post_list_view (request):
    posts=Post.objects.filter(published=True)
    
    paginator = Paginator(posts, 5)
    
    if 'page' in request.GET.keys():
        page = paginator.page(request.GET['page'])
    else:
        page = paginator.page(1)
    print(request.GET)
    
    context={'page':'posts', 'page_object': page}
    return render(request, "posts/post_list.html",context)

clicks/templates/clicks/index.html
{% load static %}

<html>

    <head>
        <title>Clicks</title>
        <script src='{% static "js/jquery.js"%}'></script>
        <script>
            $( document ).ready( function () {
                $('.send').click(function (e) {
                    e.preventDefault();
                    
                    $.ajax({
                        url: '{% url 'clicks:clicks' %} ?clicks=' + $("#count_clicks").val(),
                        type: 'GET',
                        dataType: 'json',
                        success: (data) => {
                            alert('всё сохранилось');
                        },
                        error: (error) => {
                            alert("ошибка" + error)
                        }
                    });
                });
            });
            
            
            
            let clicks = 0;
            
            function countClicks() {
                clicks++;
                $('#count_clicks').val(clicks);
            }
        </script>
    </head>

    <body>
        <button onclick='countClicks()'>Click!</button>
        <form method='get' action='.'>
            {% csrf_token %}
            <input name='clicks' id='count_clicks' value='0'>
            <input class='send' type='submit' value='Send!'>
        </form>
        <p>Сохранённые клики: {{clicks}}</p>
    </body>

</html>

posts/templates/posts/post_list.html
<html>
<head>
    <title>MyBlog</title>
</head>

<body>
<ul class="ps-3 list-unstyled pe-3">
{% for post in page_object %}
    <li>
    <div class="d-inline-flex border" style="padding: 10px 0px 0px 10px;">
        <div class="ms-3 mt-0">
                <p class="fs-2">{{ post.title }}</p>
            <p class="ps-3 pt-0 fs-3">{{ post.text|truncatechars:128 }}</p>
        </div>
    </div>
    </li>
{% endfor %}
</ul>
<div>
    <a href='?page={{ 1 }}'>&laquo;</a>
    {% for page_number in page_object.paginator.page_range %}
        {% if page_number != page_object.number %}
            <a href='?page={{ page_number }}'>{{ page_number }}</a>
        {% else %}
            {{ page_number }}    
        {% endif %}
    {% endfor %}
    <a href='?page={{page_object.paginator.num_pages}}'>&raquo;</a>
</div>
</body>

</html>